specVersion: 0.0.1
description: 'A subquery project provide common api for a polkadot network'
repository: ''
schema: ./schema.graphql
network:
  endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
  typesBundle: {
    spec: {
      kusama: {
        types: [
        {
          minmax: [
            1030,
            1031
          ],
          types:{
            IdentityInfo: {
              additional: Vec<IdentityInfoAdditional>,
                display: Data,
                legal: Data,
                web: Data,
                riot: Data,
                email: Data,
                pgpFingerprint: Option<H160>,
                image: Data
            }
          }
        }
        ],
      }
    }
  }
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleExtrinsic
          kind: substrate/CallHandler
        - handler: handleEvent
          kind: substrate/EventHandler
