specVersion: 0.0.1
description: 'A subquery project provide common api for a polkadot network'
repository: ''
schema: ./schema.graphql
network:
  endpoint: 'wss://rpc.polkadot.io'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 6711148
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleExtrinsic
          kind: substrate/CallHandler
        - handler: handleEvent
          kind: substrate/EventHandler
